export const GET_CANDIDATES = "GET_CANDIDATES";
export const GET_ANNONCES = "GET_ANNONCES";
export const GET_MULTIPOSTING = "GET_MULTIPOSTING";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_STATISTICS = "GET_STATISTICS";
export const GET_BASE_CV = "GET_BASE_CV";
